#!/bin/sh
# Toggle between monitors on a single HDMI port

# Program(s) existence check
for prog in edid-decode xuserrun "$1"; do
  if ! hash $prog 2>&- /dev/null; then
    echo ""${0##*/}": program required: "$prog"" && \
    non_prog=yes; fi; done
[ "$non_prog" = yes ] && exit 1

# Inherit variables from the configuration file
conf="/etc/hdmiaroo.conf"
conf="./hdmiaroo.conf"
if [ -r "$conf" ]; then
  source "$conf"
else
  echo ""${0##*/}": conf. non-exist: "$conf"" && exit 1; fi

echo $port $man1 $man2

# Get manufacturer information (extract edid-block [port to modeline, then
# block], decode, extract manufacturer data)
# cat /sys/class/drm/card0-HDMI-A-1/edid | edid-decode
edid () {
xrandr --verbose | sed -n '/'$port'/,/^  [0-9][0-9].*x[0-9][0-9].*/p' | \
                   grep -oP '\t\t[0-9,a-f].*' | sed 's/^\t\t//g' | edid-decode
}

edid
 
#if $

#Manufacturer: SAM Model 665 Serial Number 0

# ---

# Define admin. program if write permission is needed
#if [ ! -w "$2" ]; then
#  [ ! hash sudo 2>&- ] && { echo "${0##*/}: program required: sudo"; exit 1; }
#  sudo=sudo; fi