#!/bin/sh
# Display information about the monitor(s) on a port

# Program(s) existence check
for prog in edid-decode "$1"; do
  if ! hash $prog 2>&- /dev/null; then
    echo ""${0##*/}": program required: "$prog"" && \
    non_prog=yes; fi; done
[ "$non_prog" = yes ] && exit 1

case $1 in
  -h | --help ) echo ""{$0##*/}" [*-d] PORT - display information about the monitor on a port";;
  -v | --verbose ) xrandr --verbose | sed -n '/'$port'/,/^  [0-9][0-9].*x[0-9][0-9].*/p' | \
                   grep -oP '\t\t[0-9,a-f].*' | sed 's/^\t\t//g' | edid-decode
